POST http://localhost:5002/api/categories
Content-Type: application/json

{
  "name": "Kategori 1"
}

###
POST http://localhost:5004/products
Content-Type: application/json

{
  "name":"Test",
  "categoryId": "019c2075-97e2-7bc4-80f5-aaa77478b070"
}

###
GET http://localhost:5004/products/get-all

###
POST http://localhost:5046/create-order-async
Content-Type: application/json
idempotency-key: 2

{
  "productId": "3cd0299a-03a8-4a16-8159-b6a95c4b7807"
}

###
GET http://localhost:5046/get-all

###
POST http://localhost:5046/create-order-async
Content-Type: application/json
idempotency-key: 1

{
  "productId": "ed6765d1-cd7e-4801-8b9f-840def17bde9"
}